name: Run Unit Tests
on: push
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GdUnit4 - Test Runner Action
        uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: '4.2.1'
          version: 'latest'
          paths: 'res://test'
